dfoRanking/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("fameRanking/", include("fameRanking.urls")),
    path("", include("search.urls")),
    path("search/", include("search.urls")),
    path("admin/", admin.site.urls),
]

fameRanking/urls.py
from django.urls import path

from . import views

app_name = "fameRanking"
urlpatterns = [
    path("", views.indexView, name="index"),
]

search/urls.py
from django.urls import path

from . import views

app_name = "search"
urlpatterns = [
    path("", views.indexView, name="index"),
    path("search", views.characterResultView, name="character_result"),
]

fameRanking/models.py
from django.db import models

# Create your models here.

search/forms.py
from django import forms


class CharacterSearchForm(forms.Form):
    character_search_query = forms.CharField(label='Search Character', max_length=20)

fameRanking/views.py
from django.shortcuts import render
from decouple import config


# Create your views here.
def indexView(request):
    context = {}
    return render(request, "fameRanking/index.html", context)


# def characterFameRankingView(request):
#     context = {}
#     if request.method == 'GET':
#         api_key = config('API_KEY')

search/views.py
from django.shortcuts import render
import requests
from decouple import config

from search.forms import CharacterSearchForm


def indexView(request):
    context = {}
    return render(request, "search/index.html", context)


def characterResultView(request):
    context = {}
    if request.method == 'GET':
        form = CharacterSearchForm(request.GET)
        if form.is_valid():
            api_key = config('API_KEY')
            character_search_query = form.cleaned_data['character_search_query']

            api_url = f'https://api.dfoneople.com/df/servers/cain/characters?characterName={character_search_query}&wordType=full&apikey={api_key}'
            response = requests.get(api_url)

            if response.status_code == 200:
                character = response.json()
            else:
                character = None
            context = {
                "character": character,
            }
    return render(request, "search/characterResult.html", context)

fameRanking/templates/fameRanking/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>this is fame ranking</h1>
</body>
</html>

search/templates/search/characterResult.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Character Search Results</title>
</head>
<body>
    <h1>Character Search Results</h1>

    {% if character %}
    <p>Character Info:</p>
    <ul>
        <li>Character Name: {{ character.rows.0.characterName }}</li>
        <li>Level: {{ character.rows.0.level }}</li>
        <li>Job: {{ character.rows.0.jobName }} - {{ character.rows.0.jobGrowName }}</li>
        <li>Fame: {{ character.rows.0.fame }}</li>
    </ul>
    {% else %}
    <p>No character found with the given name.</p>
    {% endif %}

    <p><a href="{% url 'search:index' %}">Back to Search</a></p>
</body>
</html>

search/templates/search/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Character Search</title>
</head>
<body>
    <h1>Character Search</h1>
        <form method="GET" action="search">
        <input type="text" name="character_search_query" id="character_search_query" placeholder="input character name">
        <button type="submit">Search!</button>
        </form>
</body>
</html>

templates/error.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>